### ISSUE TITLE
KrakenPublic.ohcl() has a mispelling in the endpoint string

### ISSUE THREAD

**Issue by PalauReq** [delta575/trading-api-wrappers#129]
Kraken/client_public.py 26 should be 'public/OHLC' instead of 'public/OHCL'

**Comment by delta575** [comment]
Hi @PalauReq thanks letting us know.

The issue was fixed was fixed on https://github.com/delta575/trading-api-wrappers/commit/0030d91e136ffbdb9249736673276a87b9c85ba9 and released along with `v0.17.0`

Bests
